server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda-loan-service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda.bpm.admin-user:
  id: admin
  password: admin